name: Unit Tests

on:
  push:
    branches: [ "main", "developer", "feat/*" ] 
  pull_request:
    branches: [ "main", "developer" ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run All Unit Tests
        working-directory: plant-nursery-simulator 
        run: make test 
